[project]
name = "spotify-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=0.20.0",
    "python-dotenv>=1.1.1",
    "spotipy>=2.25.1",
    "streamlit>=1.47.1",
]
